[workspace]
authors = ["Paige Park <111656754+paigenpark@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "us-mortality"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.2,<4.6"
r-tidyverse = ">=2.0.0,<3"
r-here = ">=1.0.2,<2"
r-ggextra = ">=0.11.0,<0.12"
r-gridextra = ">=2.3,<3"
r-knitr = ">=1.51,<2"
r-kableextra = ">=1.4.0,<2"
r-scales = ">=1.4.0,<2"
r-ggplot2 = ">=4.0.2,<5"
r-sf = ">=1.0_24,<2"
r-spdep = ">=1.4_2,<2"
r-tigris = ">=2.2.1,<3"
r-maps = ">=3.4.3,<4"
r-ggthemes = ">=5.2.0,<6"
r-mapproj = ">=1.2.12,<2"
r-ggally = ">=2.4.0,<3"
r-zoo = ">=1.8_15,<2"
r-corrr = ">=0.4.5,<0.5"
r-ggcorrplot = ">=0.1.4.1,<0.2"
r-ggrepel = ">=0.9.6,<0.10"
r-ggfortify = ">=0.4.19,<0.5"
r-reshape2 = ">=1.4.5,<2"
r-gganimate = ">=1.0.11,<2"
r-rcolorbrewer = ">=1.1_3,<2"
r-geosphere = ">=1.5_20,<2"
r-factominer = ">=2.13,<3"
r-performanceanalytics = ">=2.0.8,<3"
r-tinyplot = ">=0.6.0,<0.7"
