---
title: "States with Zero Observation Variance by Estimation Method"
format: html
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(here)
```

```{r}
#| label: load-results
res <- readRDS(here("results", "model_fits.rds"))

state_no_obs_bfgs <- res$state_no_obs_bfgs
state_no_obs_sts <- res$state_no_obs_sts
```

```{r}
#| label: barchart
full_state_names <- tolower(state.name[match(c("AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"), state.abb)])

barchart_data <- data.frame(
  state = full_state_names,
  MARSS_BFGS = full_state_names %in% res$state_no_obs_bfgs,
  StructTS = full_state_names %in% res$state_no_obs_sts
)

long_data <- pivot_longer(barchart_data, cols = c(MARSS_BFGS, StructTS), names_to = "method", values_to = "has_no_obs")
long_data <- long_data[long_data$has_no_obs == TRUE, ]

ggplot(long_data, aes(x = method, fill = state)) +
  geom_bar() +
  labs(y = "Count of States with Estimate of Zero for Observation Variance", fill = "State", x=NULL) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
